<?php
 /**
 * GoMage.com
 *
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010 GoMage.com (http://www.gomage.com)
 * @author       GoMage.com
 * @license      http://www.gomage.com/licensing  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.0
 * @since        Class available since Release 1.0
 */
?>
<div id="gcheckout-payment-methods" class="payment-methods">
	<h2 class="gcheckout-title"><?php echo $this->__('Payment methods');?></h2>
	<script type="text/javascript">
	//<![CDATA[
	    var payment = new paymentForm('gcheckout-onepage-form');
	//]]>
	</script>
	<?php echo $this->getChildHtml('methods') ?>
		
	<?php if($advanced_content = trim($this->getChildHtml('advanced'))): ?>
	
	<div class="payment-advanced">
		
		<?php echo $advanced_content ?>
		
	</div>
	
	<?php endif;?>
</div>