<?php
 /**
 * GoMage.com
 *
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010 GoMage.com (http://www.gomage.com)
 * @author       GoMage.com
 * @license      http://www.gomage.com/licensing  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.0
 * @since        Class available since Release 1.0
 */
?>
<div class="shipping-methods">
	
	<h2 class="gcheckout-title"><?php echo $this->__('Shipping method');?></h2>
	
	<div id="gcheckout-shipping-method-available" class="shipping-methods-available">
		
		<?php echo $this->getChildHtml('available') ?>
		
	</div>
	
	<div class="shipping-additional">
		
		<?php echo $this->getChildHtml('additional') ?>
		
	</div>
	
	<?php if($advanced_content = trim($this->getChildHtml('advanced'))): ?>
	
	<div class="shipping-advanced">
		
		<?php echo $advanced_content ?>
		
	</div>
	
	<?php endif;?>
</div>