<?php
 /**
 * GoMage.com
 *
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010 GoMage.com (http://www.gomage.com)
 * @author       GoMage.com
 * @license      http://www.gomage.com/licensing  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.0
 * @since        Class available since Release 1.0
 */
 echo $this->getContent();?>
<script type="text/javascript" src="<?php echo $this->getUrl('gomage_checkout/js', array('_secure'=>true))?>"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js')?>jquery/validationEngine/jquery.validationEngine.js"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/gomage/checkout/onepage.js')?>"></script>

<script type="text/javascript">
	//<![CDATA[
	var countryRegions			= <?php echo $this->helper('directory')->getRegionJson(); ?>;
	var getMethodsUrl			= '<?php echo $this->getUrl('gomage_checkout/onepage/ajax', array('action'=>'get_methods'));?>';
	var getPaymentMethodsUrl	= '<?php echo $this->getUrl('gomage_checkout/onepage/ajax', array('action'=>'get_payment_methods'));?>';
	var getShippingMethodsUrl	= '<?php echo $this->getUrl('gomage_checkout/onepage/ajax', array('action'=>'get_shipping_methods'));?>';
	var getTotalsUrl			= '<?php echo $this->getUrl('gomage_checkout/onepage/ajax', array('action'=>'get_totals'));?>';
	var saveOrderUrl			= '<?php echo $this->getUrl('gomage_checkout/onepage/save');?>';
	
	var default_shipping_method	= '<?php echo $this->getDefaultShippingMethod()?>';
	var default_payment_method	= '<?php echo $this->getDefaultPaymentMethod()?>';
	
	var shippingMethod = false;
	var loadinfo_text = "<?php echo $this->__('Updating information, please wait...')?>";
	//]]>
</script>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

	<?php if(!$this->isCustomerLoggedIn() && $this->getCheckoutMode() != 2): ?>
	<div>
		<a href="#" class="login-button" rel="#login-block"><?php echo $this->__('Already registered? Click here to login.');?></a>
	</div>
	<div class="simple_overlay black" id="login-block" style="display:none;">
		<div class="details">
			<h2><?php echo $this->__('Customer Login')?></h2>
			<form id="gcheckout-login-form" action="<?php echo $this->getUrl('gomage_checkout/onepage/customerLogin');?>" method="post">
			<ul class="form-list">
                <li>
                    <label class="required" for="email"><em>*</em><?php echo $this->__('Email Address');?></label>
                    <div class="input-box">
                        <input type="text" title="Email Address" class="input-text required-entry" id="email" value="" name="login[username]" />
                    </div>
                </li>
                <li>
                    <label class="required" for="pass"><em>*</em><?php echo $this->__('Password');?></label>
                    <div class="input-box">
                        <input type="password" title="Password" id="pass" class="input-text required-entry validate-password" name="login[password]" />
                    </div>
                </li>
            </ul>
        	
            <div class="actions">
            	<a class="forgot-link" href="<?php echo $this->getUrl('customer/account/forgotpassword')?>"><?php echo $this->__('Forgot Your Password?')?></a>
            	<button class="button" type="submit"><span><span><?php echo $this->__('Login');?></span></span></button>
            	<div class="loadinfo" style="display:none;"><?php echo $this->__('Please wait...');?></div>
            </div>
            </form>
		</div>
	</div>
	<?php endif;?>
	<?php if($this->getConfigData('termsandconditions/enabled')):?>
	<div class="simple_overlay black" id="terms-block" style="display:none;width:<?php echo $this->getConfigData('termsandconditions/width')?>px;height:<?php echo $this->getConfigData('termsandconditions/height')?>px;">
		<div class="details">
			<div class="popup-content">
				<?php echo nl2br($this->getConfigData('termsandconditions/content'));?>
			</div>
		</div>
	</div>
	<?php endif;?>

<?php
	
	$class_mode = '';
	
	if(Mage::getSingleton('checkout/session')->getQuote()->isVirtual()){
		
		$class_mode .= ' not_shipping_mode ';
		
	}
	
	if(!Mage::getStoreConfig('gomage_checkout/general/deliverydate')){
		
		$class_mode .= ' not_deliverydate_mode ';
		
	}
	
	
?>

<div class="gcheckout-onepage-wrap <?php echo $class_mode;?>">

	<form action="" method="post" id="gcheckout-onepage-form">
		<div class="address checkout-step" id="gcheckout-onepage-address">
			
			<?php echo $this->getChildHtml('address');?>
				
		</div>
		
		<div class="gcheckout-right-col">
		
		<div class="methods checkout-step" id="gcheckout-onepage-methods">
			
			<?php echo $this->getChildHtml('methods');?>
			
		</div>
		
		<div class="review checkout-step" id="gcheckout-onepage-review">
			
			<?php echo $this->getChildHtml('review');?>
			
			<?php if($this->isEnabled('comments')):?>
			<div class="customer-comment">
				<label for="customer_comment"><?php echo  $this->__('Comments') ?></label>
				<textarea id="customer_comment" name="customer_comment" cols="50" rows="5"><?php echo $this->getCustomerComment();?></textarea>
			</div>
			<?php endif;?>
			
			<div class="advanced-options">
				
				<?php if (!$this->getQuote()->isVirtual()): ?>
				    <?php echo $this->helper('gomage_checkout/giftMessage')->getInline('onepage_checkout', $this->getQuote(), $this->getDontDisplayContainer()) ?>
				<?php endif; ?>
				<?php if($this->getConfigData('termsandconditions/enabled')):?>
				<p class="control">
					<input type="checkbox" value="1" id="accept_terms" name="accept_terms" class="validate[required] radio" />
					<label for="accept_terms"><?php echo $this->__('I accept the <a class="terms-link" href="%s" rel="#terms-block">Terms and Conditions</a>', '#terms-block');?></label>
				</p>
				<?php endif;?>
			</div>
			<div class="button-set">
				<button id="submit-btn" type="submit" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout" onclick="if(validateCheckoutForm()){clearTimeout(loadinfoTimeOut);jQuery('#gcheckout-onepage-form').unbind('submit').attr('action', saveOrderUrl).submit();}return false;"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
				<script type="text/javascript">
					function validateCheckoutForm(){
						return !jQuery.validationEngine.submitValidation(jQuery("#gcheckout-onepage-form"));
					}
				</script>
			<?php if($this->isEnabled('newsletter')):?>
				<?php if(!$this->isCustomerLoggedIn() || Mage::getModel('newsletter/subscriber')->loadByCustomer($this->getCustomer())->getStatus() != 1):?>
				
				<p class="control">
					<input type="checkbox" value="1" id="subscribe" name="subscribe" />
					<label for="subscribe"><?php echo $this->__('Subscribe to newsletter');?></label>
				</p>
				
				<?php endif;?>
			<?php endif;?>
			</div>
			

			
			
		</div>
		</div>
		<script type="text/javascript">
			var triggers = jQuery(".login-button, .terms-link").overlay({top:'center',mask: {

				// you might also consider a "transparent" color for the mask
				color: '#000',

				// load mask a little faster
				loadSpeed: 200,

				// very transparent
				opacity: 0.6
			}});
		</script>
	</form>
</div>
	