<?php
 /**
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2011 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 2.2
 * @since        Class available since Release 1.0
 */

 if(Mage::getStoreConfig('gomage_checkout/deliverydate/deliverydate')):?>

<h2 class="gcheckout-title"><span><span><?php echo $this->__('Time of Delivery');?></span></span></h2>
	<div class="lightcheckout-col-bg">
	<div class="lightcheckout-col-bg-in">
<div class="delivery-date">
		
	<?php foreach($this->getFields() as $field): ?>
	    <div class="delivery-date-<?php echo $field->getId()?> left">
	        
			<?php echo $field->getHtml() ?>
		</div>
	<?php endforeach?>
	
	<input id="dilivery-date-customeroffset-input" name="deliverydate[customer_offset]" type="hidden" class="hidden" />
</div>
</div>
</div>
<script type="text/javascript">
	
	var _date	= new Date();
	var offset	= (_date.getTimezoneOffset()*60);
		
	$('dilivery-date-customeroffset-input').value = offset;
	
</script>
<?php endif;