<?php
 /**
 * GoMage.com
 *
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010 GoMage.com (http://www.gomage.com)
 * @author       GoMage.com
 * @license      http://www.gomage.com/licensing  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.0
 * @since        Class available since Release 1.0
 */
?>
<label for="<?php echo $this->getPrefix();?>_country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
<div class="input-box input-box-country <?php echo $this->getPrefix();?>-country">
    <?php echo $this->getCountryHtmlSelect($this->getPrefix()); ?>
</div>