<?php
 /**
 * GoMage.com
 *
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010 GoMage.com (http://www.gomage.com)
 * @author       GoMage.com
 * @license      http://www.gomage.com/licensing  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.0
 * @since        Class available since Release 1.0
 */

	
	
	$input_name 	= $this->getInputName();
	$input_id		= $this->getInputId();
	$input_value	= $this->getValue();
	$input_class	= $this->getInputClass();
	$label_class	= $this->getLabelClass();
	
	$required		= $this->getIsRequired();
	$validation_type = $this->getValidationType();
	$label			= $this->getLabel();
	
	
	$input_class .= ' input-text ';
	
	if($required){
		$label_class.= 'required ';
		if(!$validation_type){
			$input_class .= 'required-entry'.' ';
		}else{
			$input_class .= $validation_type.' ';
		}
		
	}
	
?>
<label for="<?php echo $input_id;?>" class="<?php echo $label_class;?>"><?php if($required):?><em>*</em><?php endif;?><?php echo $this->__($label); ?></label>
<div class="input-box <?php echo $input_id;?>">
    <input type="text" name="<?php echo $input_name;?>" id="<?php echo $input_id;?>" value="<?php echo $this->htmlEscape($input_value) ?>" title="<?php echo $label; ?>" class="<?php echo $input_class;?>" />
</div>