<?php
 /**
 * GoMage.com
 *
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010 GoMage.com (http://www.gomage.com)
 * @author       GoMage.com
 * @license      http://www.gomage.com/licensing  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.0
 * @since        Class available since Release 1.0
 */
?>
<label for="<?php echo $this->getPrefix();?>_region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
<div class="input-box input-box-region <?php echo $this->getPrefix();?>-region">
	<?php if($this->isEnabled('country_id')):?>
    <select id="<?php echo $this->getPrefix();?>_region_id" name="<?php echo $this->getPrefix();?>[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate[required]" style="display:none;">
        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
    </select>
    <script type="text/javascript">
    //<![CDATA[
        $('<?php echo $this->getPrefix();?>_region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
    //]]>
    </script>
    <input type="text" id="<?php echo $this->getPrefix();?>_region" name="<?php echo $this->getPrefix();?>[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
    <?php else:?>
    <input type="text" id="<?php echo $this->getPrefix();?>_region" name="<?php echo $this->getPrefix();?>[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" />
    <?php endif;?>
</div>