<?php
 /**
 * GoMage.com
 *
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010 GoMage.com (http://www.gomage.com)
 * @author       GoMage.com
 * @license      http://www.gomage.com/licensing  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.0
 * @since        Class available since Release 1.0
 */
 echo $this->getChildHtml('billing');?>

<?php if(!Mage::getSingleton('checkout/session')->getQuote()->isVirtual() && intval(Mage::getStoreConfig('gomage_checkout/general/different_shipping_enabled'))): echo $this->getChildHtml('shipping'); endif;?>