<div class="simple_overlay" id="gcheckout-payment-centinel"
     style="display:none;width:<?php echo intval(Mage::getStoreConfig('gomage_checkout/address_fields/secure_window_width')) ?>px;height:<?php echo intval(Mage::getStoreConfig('gomage_checkout/address_fields/secure_window_height')) ?>px;">
    <div class="glc-popup-content">
        <a class="close" onclick="checkout.hideCentinel();return false;">&#x2715;</a>

        <div class="details">
            <div class="popup-content" id="gcheckout-payment-centinel-html">
            </div>
        </div>
    </div>
</div>