<?php
 /**
 * GoMage.com
 *
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010 GoMage.com (http://www.gomage.com)
 * @author       GoMage.com
 * @license      http://www.gomage.com/licensing  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.0
 * @since        Class available since Release 1.0
 */
 if(!Mage::getSingleton('checkout/session')->getQuote()->isVirtual()):?>

<?php echo $this->getChildHtml('shipping_method');?>

<?php endif;?>

<?php echo $this->getChildHtml('payment');?>
