<?php
 /**
 * GoMage.com
 *
 * GoMage LightCheckout Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010 GoMage.com (http://www.gomage.com)
 * @author       GoMage.com
 * @license      http://www.gomage.com/licensing  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 1.0
 * @since        Class available since Release 1.0
 */
?>
<label for="<?php echo $this->getPrefix();?>_street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
<div class="input-box">
	<input type="text" title="<?php echo $this->__('Street Address') ?>" name="<?php echo $this->getPrefix();?>[street][]" id="<?php echo $this->getPrefix();?>_street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text validate[required]" />
</div>
<?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
<div class="input-box">
	<input type="text" title="<?php echo $this->__('Street Address '.$_i) ?>" name="<?php echo $this->getPrefix();?>[street][]" id="<?php echo $this->getPrefix();?>_street<?php echo $_i?>" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($_i)) ?>" class="input-text" />
</div>
<?php endfor;?>