<?php $helper = Mage::helper('gomage_checkout');?>
(function($) {
	$.fn.validationEngineLanguage = function() {};
	$.validationEngineLanguage = {
		newLang: function() {
			$.validationEngineLanguage.allRules = 	{"required":{    			// Add your regex rules here, you can take telephone as an example
						"regex":"none",
						"alertText":"<?php echo $helper->__('* This field is required');?>",
						"alertTextCheckboxMultiple":"<?php echo $helper->__('* Please select an option');?>",
						"alertTextCheckboxe":"<?php echo $helper->__('* This checkbox is required');?>"},
					"length":{
						"regex":"none",
						"alertText":"<?php echo $helper->__('*Between ');?>",
						"alertText2":"<?php echo $helper->__(' and ');?>",
						"alertText3": "<?php echo $helper->__('characters allowed');?>"},
					"maxCheckbox":{
						"regex":"none",
						"alertText":"<?php echo $helper->__('* Checks allowed Exceeded');?>"},	
					"minCheckbox":{
						"regex":"none",
						"alertText":"<?php echo $helper->__('* Please select ');?>",
						"alertText2":"<?php echo $helper->__(' options');?>"},	
					"confirm":{
						"regex":"none",
						"alertText":"<?php echo $helper->__('* Your field is not matching');?>"},		
					"telephone":{
						"regex":"/^[0-9\-\(\)\ ]+$/",
						"alertText":"<?php echo $helper->__('* Invalid phone number');?>"},	
					"email":{
						"regex":"/^[a-zA-Z0-9_\.\-]+\@([a-zA-Z0-9\-]+\.)+[a-zA-Z0-9]{2,4}$/",
						"alertText":"<?php echo $helper->__('* Invalid email address');?>"},	
					"date":{
                         "regex":"/^[0-9]{4}\-\[0-9]{1,2}\-\[0-9]{1,2}$/",
                         "alertText":"<?php echo $helper->__('* Invalid date, must be in YYYY-MM-DD format');?>"},
					"onlyNumber":{
						"regex":"/^[0-9\ ]+$/",
						"alertText":"<?php echo $helper->__('* Numbers only');?>"},	
					"noSpecialCaracters":{
						"regex":"/^[0-9a-zA-Z]+$/",
						"alertText":"<?php echo $helper->__('* No special caracters allowed');?>"},	
					"ajaxUser":{
						"file":"validateUser.php",
						"extraData":"name=eric",
						"alertTextOk":"<?php echo $helper->__('* This user is available');?>",	
						"alertTextLoad":"<?php echo $helper->__('* Loading, please wait');?>",
						"alertText":"<?php echo $helper->__('* This user is already taken');?>"},	
					"ajaxName":{
						"file":"validateUser.php",
						"alertText":"<?php echo $helper->__('* This name is already taken');?>",
						"alertTextOk":"<?php echo $helper->__('* This name is available');?>",	
						"alertTextLoad":"<?php echo $helper->__('* Loading, please wait');?>"},		
					"onlyLetter":{
						"regex":"/^[a-zA-Z\ \']+$/",
						"alertText":"<?php echo $helper->__('* Letters only');?>"},
					"validate2fields":{
    					"nname":"validate2fields",
    					"alertText":"<?php echo $helper->__('* You must have a firstname and a lastname');?>"}	
					}	
					
		}
	}
})(jQuery);

jQuery(document).ready(function($) {	
	$.validationEngineLanguage.newLang();
});